apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorder
spec:
  selector:
      matchLabels:
        app: captureorder
  template:
      metadata:
        labels:
            app: captureorder
      spec:
        imagePullSecrets:
        - name: acr-auth	
        containers:
        - name: captureorder
          image: deviwantacr.azurecr.io/captureorder:#{Build.BuildId}#
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: TEAMNAME
            value: "team-JCG"
          - name: MONGOHOST
            value: "#{captureorder-variables.mongoHost}#"
          - name: MONGOUSER
            value: "#{captureorder-variables.mongoUser}#"
          - name: MONGOPASSWORD
            value: "#{captureorder-variables.mongoPassword}#"
          ports:
          - containerPort: 8080
